server:
  port: 8081
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database: postgresql
    generate-ddl: true

jwt:
  prefix: Bearer
  expiration: 72000
  secret: springboot
  authorities:
    key: authorities

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
