server:
  port: 8762

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: delivery-service
          uri: http://localhost:9001/
          predicates:
            - Path=/deliveries/**
        - id: user-service
          uri: http://localhost:9002/
          predicates:
            - Path=/users/**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}